### ISSUE TITLE
A python file that has no .py extension is rejected

### ISSUE THREAD

**Issue by jdevera** [google/yapf#126]
I run `yapf myscript`, where `myscript` is a standalone python script, and I get this:

```
Traceback (most recent call last):
  File "/home/jdevera/.local/bin/yapf", line 9, in <module>
    load_entry_point('yapf==0.1.6', 'console_scripts', 'yapf')()
  File "/home/jdevera/.local/lib/python2.7/site-packages/yapf/__init__.py", line 206, in run_main
    sys.exit(main(sys.argv))
  File "/home/jdevera/.local/lib/python2.7/site-packages/yapf/__init__.py", line 138, in main
    raise YapfError('Input filenames did not match any python files')
yapf.YapfError: Input filenames did not match any python files
```

**Comment by hayd** [comment]
Perhaps this is a silly question, but why don't you want to use a .py file extension?

**Comment by gwelymernans** [comment]
+1 @hayd's comment

**Comment by jdevera** [comment]
Well, for python files inside a project with several files, modules, etc, I do use the .py extension, but for standalone scripts that are intended to be used as commands, the .py at the end is just noise. You are using a command, you don't care what it's written in.

In this case I had to create a symlink to the script but that should not be "the way", if you say `python thisfile` you will get it executed with python, the same should happen here.

In understand that for the recursive mode, the tool uses this to quickly filter and not format non-python files, but

   a) There are better ways to determine if a file is a python file (e.g. using `file`)
   b) Perhaps the filtering could be enabled only in recursive mode

**Comment by gwelymernans** [comment]
I think you should be able to create a zip file of your project with any name you want and, as long as there's a `__main__.py` file in the top-level directory, then you don't need the extension.

a) I'm not sure how I would use `file` to determine if the file is truly a Python file.
b) I don't think that filtering only in recursive mode will work. It's almost certainly to fail for someone. And what do we do if they do something like `yapf *`, which should be valid and formatting only Python files. We just run into too many issues this way.

Probably the best we could do is to do something similar to `autopep8`, where it reads the first line to see if there's a Python shebang on it. But otherwise, I don't see this as being actionable.

**Comment by jdevera** [comment]
zip file, directory, __main__.py? Overly complicated for a standalone script that fits in one screen! And just for the benefit of being formatted.
Take this file, for instance:
```
↬  head -n2 sluggify 
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

See `file`:
```
 ↬  file sluggify 
sluggify: Python script, ASCII text executable
```

I bet what file is doing is what you mention in your last suggestion, which is already quite an improvement over the current situation.

I don't really understand why this request seems to be received as so "alien", to the point of closing the issue in the middle of the discussion. How do I interpret that?

Run this on your system to see how common this is:

```
grep -H '^#!.*python' /usr/bin/*
```

**Comment by gwelymernans** [comment]
Try it now with the newest check-in.

**Comment by jdevera** [comment]
works like a charm, thanks, much appreciated!

**Comment by gwelymernans** [comment]
No problem. :-)
