### ISSUE TITLE
Exclude files/directories

### ISSUE THREAD

**Issue by hayd** [google/yapf#128]
You want to be able to run `yapf *` and have it work on all your files, but usually you don't want yapf to change build/ files (or .tox/) files etc. There should be a way to exclude certain directories.

It would be nice if this wasn't something you had to remember to type e.g. add exclude with #108, or these files should be excluded by looking at the .gitignore (probably that's too magical!).

**Comment by gwelymernans** [comment]
I don't think we should rely upon `.gitignore`. Once #108 has been hammered out, this might fit in there.

**Comment by eliben** [comment]
ISTM that the functionality of _finding_ files is orthogonal to the functionality of _formatting_ them, and ignoring dirs belongs strictly to the former. There are different things you may want to ignore - dirs, certain file patterns, etc. Why not just pipe `find` into `xargs yapf`, or even better something like pss [https://github.com/eliben/pss] :-) Sorry about the plug, but it's very relevant, because pss specifically supports everything you may imagine & want in terms of finding source code, auto-ignores certain directories and allows to configure more dirs to ignore, does recursive searches ,etc:

    pss --ignore-dir=foo -f --python | xargs yapf ...

I'm not saying `pss` is required here - this can be redone as a longer `find` / `grep` incantation. For a given project this can be just part of some `reformat.sh` script.

Unix(y) utilities are supposed to be composable and not reinvent each other's functionality ;-)

**Comment by hayd** [comment]
Oooh pss looks nice, will try out replacing ack ! :)

It's not that I'm adverse to piping things, I always pipe my diffs to [cdiff](https://pypi.python.org/pypi/cdiff) :). But I would say, since there's already a recursive search, excluding seems a reasonable extension.

(Must be wary of feature creep, but exclude and jobs are the only (non-style) "missing" autopep8 args.)

**Comment by gwelymernans** [comment]
So basically, it's just adding a nicety for the user. Adding a `--exclude` flag, like with `autopep8`, could be just the thing. Thoughts?

**Comment by hayd** [comment]
...ahem, yes! Somehow I omitted that in the OP - this was precisely what I had in mind! That is, --exclude flag and (after 108) *something* in your .style.yapf. :)

**Comment by hayd** [comment]
Now we have #108, perhaps we could extend it with an options section:
```
[options]
files = setup.py,yapf,yapftest
recursive = True
```
Use these if no files argument is passed. Too magical?

**Comment by gwelymernans** [comment]
A bit too magical. Without a file argument, it should read from `stdin`. I'm a bit concerned that if we allow them to specify command line options in this file then there would be no way to override them on the command line, or at the least it would be awkward to do so.

Let's start with a flag that will exclude files and directories, one that takes a comma-separated list, and go from there. Do you want to do the honors? :-)
