### ISSUE TITLE
not work when there is a '\' at the end of the line

### ISSUE THREAD

**Issue by fayeshine** [google/yapf#219]
should also try to format this

**Comment by obmarg** [comment]
Yeah, \ continuations seem to stop yapf from doing anything.

Both these examples are left alone:

```
test = \
       blah(
           'something', 'whatever').first()

test = \
       blah(
           'something',
           'whatever'
).first()
```

Would prefer the \ to be removed personally.

**Comment by gwelymernans** [comment]
This is intentional. Once we encounter a `\`, we assume that the programmer knew what they were doing re the formatting and therefore do nothing with the line. It might be possible to make this a configurable option, i.e., if set we would reformat the line removing the `\`, but it's likely to run into major issues for people. For instance, it could mess something like this up making the if-then conditional longer than 79 columns:

```
  if this_is_a_really_long_function_name(arg1, arg2, arg3) and \
     this_is_another_really_long_function_name(arg4, arg5, arg6):
     pass
```
