### ISSUE TITLE
Please normalize implicit string continuations

### ISSUE THREAD

**Issue by bukzor** [google/yapf#276]
Input:

```
a = (
    "foo"
    "bar"
)
```

Desired output:
```
a = 'foobar'
```

Actual output:
```
a = ("foo" "bar")
```

**Comment by gwelymernans** [comment]
This way lies madness. :-)

In order to do this correctly, the concatenated strings would need to be wrapped at the column limit. And while that's something that `textwrap` can do, I know from experience that handling all of the edge cases is a horror show.

But this also goes against my philosophy for yapf. yapf is strictly a formatter. It won't add or remove items from the token stream[`*`]. The reason for this philosophy is so we can better ensure that there are no semantic changes to the code after yapf's done with it. This is why we don't add a backslash or parentheses to an expression when it could potentially create better formatting for the code.

`*` There is one instance where yapf adds "pseudo" parentheses inside of maps, but they are never printed and are there solely to help formatting decisions.
