### ISSUE TITLE
DEDENT_CLOSING_BRACKETS does not seem to work if arguments fit in line

### ISSUE THREAD

**Issue by wheerd** [google/yapf#349]
I am getting somewhat inconsistent formatting on code like this:

```python
def long_function_name(argument1: Tuple[str, int], argument2: List[str]) -> Iterator[str]:
    pass

def ever_longer_function_name(argument1: Tuple[str, int], argument2: List[str]) -> Iterator[str]:
    pass
```

My `setup.cfg`:
```ini
[yapf]
based_on_style = pep8
coalesce_brackets = True
dedent_closing_brackets = True
split_penalty_after_opening_bracket = 0
split_before_first_argument = true
```

The result is this:
```python
def long_function_name(argument1: Tuple[str, int],
                       argument2: List[str]) -> Iterator[str]:
    pass


def ever_longer_function_name(
        argument1: Tuple[str, int], argument2: List[str]
) -> Iterator[str]:
    pass
```

However, i would prefer the second style for the first example as well. I was expecting the `split_before_first_argument` option to have exactly that effect, but it does not seem to work.

With type annotations, the function signatures can get significant length other than their arguments. so this happens quite frequently in my code base. This issue seems to happen if the arguments fit in one line, but the full signature does not. If the arguments are longer than one line, it works fine.

I am using version 0.14.0.

**Comment by hugo-ricateau** [comment]
Turns out that the return type annotation seems to be "neglected"; and, for an obscure reason, only when there is at least one bracket in the arguments list.

Using the style
```
[yapf]
based_on_style = pep8
dedent_closing_brackets = true
```
with `yapf 0.23.0`

The code
```
#                                                                              | line finishes right before the pipe
def function(first_argument_xxxxxxxxxxxxxx=(0, ), second_argument=None) -> None:
    pass
```
is reformatted to
```
def function(first_argument_xxxxxxxxxxxxxx=(0, ),
             second_argument=None) -> None:
    pass
```
instead of
```
def function(
    first_argument_xxxxxxxxxxxxxx=(0, ), second_argument=None
) -> None:
    pass
```
As I understand it, while determining if all the arguments (as well as the closing parenthesis and colon) fit on one line, the return type annotation is neglected. So the `first_argument_xxxxxxxxxxxxxx=(0, ),` is added right after the opening parenthesis. However, because of the annotation, there is an unexpected extra penalty for placing `second_argument=None) -> None:` on that line too, hence the weird split.

For instance, both
```
#                                                                              |
def function(first_argument_xxxxxxxxxxxxx=(0, ), second_argument=None) -> None:
    pass
```
and
```
#                                                                              |
#                                                    ..., second_argument=None): <- ':' exceeds the pep8 default line length
def function(first_argument_xxxxxxxxxxxxxxxxxxxxxx=(0, ), second_argument=None) -> None:
    pass
```
are formatted as expected, whereas
```
#                                                                              |
#                                                   ..., second_argument=None):
def function(first_argument_xxxxxxxxxxxxxxxxxxxxx=(0, ), second_argument=None) -> None:
    pass
```
is not.

What is really weird is that the issue relies on the presence of a bracket:
- the issue remains when replacing `()` by either `[]` or `{}`,
- while everything is formatted as expected when replacing `=(0, )` by `=10101` for instance.

@gwelymernans, could you mark this as a `bug`?

**Comment by hugo-ricateau** [comment]
Fixed. I'll publish a PR shortly.
