### ISSUE TITLE
yapf --style=pep8 gets confused by tabs and only converts some of them to spaces

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#43]
Given the following where the indents are tabs:

    def strip_fragment(url):
    	"""
    	"""
yapf converts the first tab into spaces but not the second. 

Tabs are merely discouraged, but mixing tabs with spaces is definitely illegal in pep8.

**Comment by eliben** [comment]
yapf actually always replaces tabs with spaces. What happens here is that the second tab is inside a string, which is why yapf leaves it alone. So this isn't technically a violation, because tabs within strings are not forbidden by PEP8.

That said, perhaps *leading* tabs like in this example can be handled differently.

**Comment by DRMacIver** [comment]
Oh yes, you're quite right. I was failing to parse that correctly myself, sorry.

I think yapf is doing the right thing here (and that replacing a tab inside a string would be very much the wrong thing) and the pep8 checker is not. I'm inclined to close this and file a bug with them. What do you think?

**Comment by DRMacIver** [comment]
In fact, this is already filed as a bug in pep8: https://github.com/jcrocholl/pep8/issues/376
