### ISSUE TITLE
yapf does not explicitly handle different encodings

### ISSUE THREAD

**Issue by DRMacIver** [google/yapf#49]
yapf will error if you run it on a file that cannot be handled by the encoding set by your LANG environment variable. e.g. consider the following file:

    # encoding: utf-8

    x = "☃"

If you set LANG=C and run yapf on it this will crash with

        Traceback (most recent call last):
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 170, in _run_module_as_main
            "__main__", mod_spec)
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/runpy.py", line 85, in _run_code
            exec(code, run_globals)
          File "/home/david/yapf/yapf/__main__.py", line 18, in <module>
            sys.exit(yapf.main(sys.argv))
          File "/home/david/yapf/yapf/__init__.py", line 102, in main
            print_diff=args.diff)
          File "/home/david/yapf/yapf/__init__.py", line 124, in FormatFiles
            filename, style_config=style_config, lines=lines, print_diff=print_diff)
          File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 59, in FormatFile
            original_source = ReadFile(filename, logging.warning)
          File "/home/david/yapf/yapf/yapflib/yapf_api.py", line 142, in ReadFile
            source = fd.read()
          File "/home/david/.pyenv/versions/3.4.2/lib/python3.4/encodings/ascii.py", line 26, in decode
            return codecs.ascii_decode(input, self.errors)[0]
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 24: ordinal not in range(128)

(Took me forever to figure out this was what was going on here. I was experiencing a lot of crashes when running yapf in a subprocess but couldn't reproduce them. Finally figured out it was that the environment was getting overridden)

**Comment by gotgenes** [comment]
yapf needs to open source files using [`codecs.open`](https://docs.python.org/library/codecs.html#codecs.open), and accept an optional explicit file encoding parameter on the command line interface, as well as for any functions exposed in the API that create a file handle. See #19 for an example usage.

**Comment by DRMacIver** [comment]
I learned about tokenize.open recently. It handles encoding comments in python source files to infer the correct file encoding.

I think it's python 3 only but the source code might be open source in a way you could use.

**Comment by gotgenes** [comment]
Guessing encoding based on the header comment in the source file would be convenient. Keep in mind, though, that it's not always accurate. See [Fact of Life 5: Sometimes you are told wrong](http://nedbatchelder.com/text/unipain.html). This is why it's important to allow users to pass it in explicitly.

**Comment by DRMacIver** [comment]
Right, but the correct way to pass it in explicitly is to fix your source code so it's not lying. :-) yapf already does not correctly reformat syntactically invalid source after all.

**Comment by gotgenes** [comment]
I hadn't thought of it that way, but you make a good point. For convenience, if the user provides a file with encoding declared inside the file via a magic comment matching one of the [PEP 263 specifications](https://www.python.org/dev/peps/pep-0263/), then yapf should read this comment line and select this encoding for decoding the file.

I still advocate for yapf and its API to accept encoding as an explicit parameter when reading source files, as there are still cases for which it would be useful; for example, when the source file does not contain an explicit encoding magic comment, or when [`tokenize.open`](https://docs.python.org/3/library/tokenize.html#tokenize.open) (and by dependency, [`tokenize.detect_encoding`](https://docs.python.org/3/library/tokenize.html#tokenize.detect_encoding)) guess incorrectly. Otherwise, yapf will force users to declare a magic comment to any source file they run it through the tool, which is very opinionated (even though I agree with it) and may overstep the scope of this tool. Such opinion seems better relegated to style checkers like [pep8](https://pep8.readthedocs.org/en/latest/) and [Pylint](http://www.pylint.org/).

**Comment by asottile** [comment]
Does it make sense to maintain the original encoding or to fix it to something reasonable (utf-8)?  In py2 it kind of makes sense to maintain the original encoding as bytestrings will be encoded using that encoding.  For py3 there's very little reason to specify a source encoding afaict.

Also if we're going by how the interpreter handles non-ascii (non-utf-8 py3) I think it's reasonable to reject files without an explicit encoding if they are not UTF-8).

Also probably relevant to this discussion: https://www.python.org/dev/peps/pep-3120/

Here's how we detect encoding in another project I've worked on (also dealing with 2to3 + automatic refactorings!) https://github.com/bukzor/RefactorLib/blob/master/refactorlib/python/parse.py#L5-L22

I'm interested in working on this issue.

**Comment by gwelymernans** [comment]
I think that this is taken care of by: 1d42a266d23394ff917d89aeab6f75a4d80e09c5
