### ISSUE TITLE
Make it pip installable

### ISSUE THREAD

**Issue by sametmax** [google/yapf#5]
Downloading it and running setup.py make deployment harder than it should be.

**Comment by poros** [comment]
+1

**Comment by meshy** [comment]
+1

**Comment by gmr** [comment]
+1

**Comment by cuerty** [comment]
+1

**Comment by pignacio** [comment]
+1

**Comment by flyte** [comment]
+2 :)

**Comment by renstrom** [comment]
Meanwhile:

    pip install https://github.com/google/yapf/archive/master.zip           # master

    pip install git+git://github.com/google/yapf.gi@<commit_hash>t#egg=yapf # specific commit

    pip install git+git://github.com/google/yapf.git#egg=yapf               # master

**Comment by jjangsangy** [comment]
Use the wheel format.

If you're gonna make it pip installable, might as well hit 2 birds with one stone.

**Comment by cedk** [comment]
+1

**Comment by renstrom** [comment]
https://pypi.python.org/pypi/yapf

**Comment by gmr** [comment]
@renstrom see #11

**Comment by eliben** [comment]
YAPF is not on PyPI yet (or at least, we didn't release it there), and we definitely plan to put it there at some point. Right now, we're considering it an alpha release and want to stabilize a tool a bit more before we feel confident enough publishing it outside Github.

Bill will talk about YAPF at PyCon in a couple of weeks, and we plan to have an initial release up on PyPI by that time.

**Comment by gotgenes** [comment]
> Right now, we're considering [YAP an alpha release and want to stabilize a tool a bit more before we feel confident enough publishing it outside Github.

pip and PyPI already have the mechanisms to support pre-releases of packages. [pip has supported installation of pre-release packages on PyPI since pip v1.4, via the `--pre` flag](https://pip.pypa.io/en/latest/reference/pip_install.html#pre-release-versions). (Without the `--pre` flag, pip will only install the latest stable version, if one exists, and error out if no stable release exists yet.)  [PEP-440](https://www.python.org/dev/peps/pep-0440/) contains the semantic versioning rules used by pip and Python packaging in general, including [documentation on how to specify a pre-release version](https://www.python.org/dev/peps/pep-0440/#pre-releases).

**Comment by sbc100** [comment]
+1

**Comment by eliben** [comment]
https://pypi.python.org/pypi/yapf
