### ISSUE TITLE
break after a binary operator, not before

### ISSUE THREAD

**Issue by smurfix** [google/yapf#526]
Flake8 warning W503: line break before binary operator
```
        if self._token is not None and (self._some_deferred
                                        or threading.current_thread() != self._thread):
            self._some_deferred += 1
```
Manually moving the `or` to the first line doesn't take, yapf moves it back.
Is there a way to fix that?

**Comment by AWhetter** [comment]
A line break _should_ be before a binary operator. PEP8 was updated to expect binary operators before a line break (https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator) and the flake8 warning has since been turned off by default (https://github.com/PyCQA/pycodestyle/pull/499).

**Comment by smurfix** [comment]
Ah, OK.

**Comment by darrenleeweber** [comment]
Is `%` a binary operator?  It seems `yapf` breaks after it.
