### ISSUE TITLE
yapf not splitting long lines without brackets

### ISSUE THREAD

**Issue by apbard** [google/yapf#680]
I would expect this: 
```python3
sad= myvariable1 + myvariable2 + myvariable3 + myvariable4 + myvariable5 + myvariable6 + myvariable7 + myvariable8 + myvariable9
```

to be split and format like this:
```python3
sad = (myvariable1 + myvariable2 + myvariable3 + myvariable4 + myvariable5 +
       myvariable6 + myvariable7 + myvariable8 + myvariable9)
```

but with the current master version (a4a48d89750cff7ac5239e314b0820d7f3bf408a) is left untouch.
Am I missing something?

**Comment by kamahen** [comment]
This would require yapf changing the source code, which might not be a good idea.

Maybe that should be an option? SPLIT_LONG_LINES_BY_ADDING_PARENS
But I suspect it could be tricky in the general case to figure out where to add the parens. It's not just assignment statements --- if-statements, import statements, etc. etc.

**Comment by apbard** [comment]
Yes, you are right. This is just an example. 
I also agree that changing the code could be tricky but not doing that means that we don't have the guarantee that the output will be pep8 compliant. 
This is maybe fine but I would at least document it and/or raise a warning to tell the user that there is something that should be manually fixed.

Anyway, others formatters (e.g., [here](https://github.com/ambv/black/blob/master/black.py#L2709])) seems to have found a way to do it.

**Comment by gwelymernans** [comment]
I'm adamant that YAPF should not change the token stream. That way lies madness. (Early on, I changed YAPF to add "pseudo" parentheses around dictionary values so that formatting them is easier. However, it's the source of many bugs and I've regretted it ever since.) I want YAPF's changes to be as safe as possible. If I allow YAPF to change the token stream, then it's entirely possible to subtly change the semantics of a program.

That said, if you want to do something like this, you may want to write a lib2to3 "fixer" that can do it for you (it's actually pretty easy to write one of them).

**Comment by apbard** [comment]
@gwelymernans I agree with you. Moreover, are usually easy to fix manually. I have just submitted a [PR](#681 ) to document this choice in the FAQ.
