### ISSUE TITLE
SPLIT_PENALTY_IMPORT_NAMES returning error

### ISSUE THREAD

**Issue by chrisspen** [google/yapf#750]
If I specify:

    SPLIT_PENALTY_IMPORT_NAMES = true

in my `.style.yapf`, yapf returns the error:

    yapf: 'true' is not a valid setting for SPLIT_PENALTY_IMPORT_NAMES.

which doesn't match the documentation, which doesn't mention what values the knob accepts, implying it's a simple boolean.

**Comment by gwelymernans** [comment]
All `SPLIT_PENALTY_*` options take an integer value (the amount of penalty a split incurs). It doesn't really lend itself to a boolean value type.

**Comment by Spenhouet** [comment]
@gwelymernans This still does not explain what value range needs to be set here. What is the default? If I want more splitting, do I have to increase the integer? How much? What if I want imports always to be split? What do I need to set?

**Comment by gwelymernans** [comment]
The default for `SPLIT_PENALTY_IMPORT_NAMES` is `0`. This means that there's no resistance to splitting import names. If you want it to always split, then we will probably need to create another option. If you want, you can try negative values for the splitting (I haven't tried this, but theoretically work).

**Comment by Spenhouet** [comment]
@gwelymernans Thank you for the explanation.

I asked because I have a very inconsistent behavior where for example this:

```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey, CaseInsensitiveSet,
                                                  UpperLowerBound)
```

flip flops with this:

```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey,
                                                  CaseInsensitiveSet, UpperLowerBound)  
```

every time I press save.

I even experience that code I duplicated or deleted.

The above import also formats to this:

```
from utils.python_utils import (CaseInsensitiveDict, CaseInsensitiveKey,
                                                  CaseInsensitiveSet, UpperLowerBound)
    UpperLowerBound)
```

What is no longer correct.

But I just realized that this seems to be a conflict between `yapf` and VS code's organize imports on save.
This is really bad and I would like it to get fixed but I'm not sure at who's end something needs to change.
If I turn one of both of, the other works fine. Then, the `yapf` formatting is consistent.

@gwelymernans Should I report this to the VS code team? Or should I create a new issue on the `yapf` repo?


My problem is with this VS code settings:

```
{
    "editor.formatOnSave": true,
    "python.formatting.provider": "yapf",
    "python.formatting.yapfArgs": [
        "--style",
        "{based_on_style: google, column_limit: 100}"
    ],
    "[python]": {
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        }
    }
}
```

**Comment by Spenhouet** [comment]
Ok, this does not seem to have anything to do with formatting at all. This is only the organizeImports feature. I created an issue here: https://github.com/microsoft/vscode/issues/89984
So my issue has nothing to do with `yapf`. Sorry to bother you with this.

**Comment by manugarri** [comment]
@bwendling setting a negative number does NOT work unfortunately.
