### ISSUE TITLE
what yapf style matches black?

### ISSUE THREAD

**Issue by ali5h** [google/yapf#752]
does anyone have a style that matches what black produces?
I have this but it is not a full match
```
[style]
based_on_style = pep8
column_limit = 88
DEDENT_CLOSING_BRACKETS = true
```

**Comment by kamahen** [comment]
It's not entirely possible to match black because black does things like add trailing commas and add parentheses (to get rid of backslash continuations) but yapf has a philosophy of not changing the source. Also, in my observation, black likes to make lists into one-per-line; this isn't contrary to PEP8 but it annoys me.
