### ISSUE TITLE
why does yapf-api adding space outside lines when i use FormatCode or FormatFile?

### ISSUE THREAD

**Issue by btyh17mxy** [google/yapf#82]

**Comment by gwelymernans** [comment]
Do you have an example of what it's doing that it shouldn't be doing?

**Comment by btyh17mxy** [comment]
I try yapf work on the following code
``` python
from yapf.yapflib.yapf_api import FormatCode
from yapf.yapflib import style

print FormatCode(un_code)
a=9+0
class A:
    def c():
        print 88888
    def b():
        l = {"asdf":2}
        h = 9+0
        asd = d*3
```
and when I run `print FormatCode(str_code, lines=[(10,12)])` ,I get result like this
``` python
from yapf.yapflib.yapf_api import FormatCode
from yapf.yapflib import style

print FormatCode(un_code)
a = 9 + 0
class A:
    def c():
        print 88888
    def b():
        l = {"asdf": 2}
        h = 9 + 0
        asd = d * 3
```
and get following result when I call FormatCode without the parameter 'lines'
``` python
from yapf.yapflib.yapf_api import FormatCode
from yapf.yapflib import style

print FormatCode(un_code)
a = 9 + 0


class A:
    def c():
        print 88888

    def b():
        l = {"asdf": 2}
        h = 9 + 0
        asd = d * 3
```

I suppose using "lines" will not do anything outside the range that I pass to FormatCode. But as you can see, it has add some space in `a=9+0`. The only diffrence between with "lines" and without is when I using "lines" it will not add any empty line out of those lines. 
And I think this is kind of confuseing. Or it just I did it wrong?

**Comment by gwelymernans** [comment]
Correct, using `lines` should cause no changes outside of the line range (there are times when it does modify things outside of the ranges, but it only does that for semantic correctness).

The newlines you see when you don't specify the `lines` parameter are required by the style guide. The spaces in `a = 9 + 0` are there also because of the style guide, which encourages people to use horizontal whitespace in these situations.
