### ISSUE TITLE
Is is better to fit arguments and import lists on a single continuation line?

### ISSUE THREAD

**Issue by anntzer** [google/yapf#84]
Currently, yapf breaks down long argument and import lists over multiple lines:
```
$ echo 'a_very_long_or_indented_function_name_yada_yada(long_argument_1, long_argument_2)' | yapf
a_very_long_or_indented_function_name_yada_yada(long_argument_1,
                                                long_argument_2)
$ echo "from a_very_long_or_indented_module_name_yada_yada import (\nlong_argument_1, long_argument_2)" | yapf
from a_very_long_or_indented_module_name_yada_yada import (long_argument_1,
                                                             long_argument_2)
```
I tend to prefer trying to put all arguments on the same line if possible, ie.
```
a_very_long_or_indented_function_name_yada_yada(
    long_argument_1, long_argument_2)
from a_very_long_or_indented_module_name_yada_yada import (
    long_argument_1, long_argument_2)
```
A quick look at PEP8 and the Google style guide did not reveal anything about this, and I guess it really depends on the semantics of the arguments for the function anyways.  For long import lists, though, I think the second choice (restarting at an indent of 4) is clearly preferable, as it avoids spreading all the names over many lines using just the last few columns.

As a side note (and real bug), yapf won't break long import lists if they have no parentheses:
```
$ echo "from a_very_long_or_indented_module_name_yada_yada import long_argument_1, long_argument_2" | yapf
from a_very_long_or_indented_module_name_yada_yada import long_argument_1, long_argument_2
```
where the introduction of parentheses can help.

**Comment by gwelymernans** [comment]
There are two things that YAPF avoids doing:

- Adding parentheses to statements, and
- Adding a backslash-newline to continue code on the next line

So the last thing is "intended behavior". You will have to add either the parentheses or backslash-newline yourself so that YAPF will know what to do.

As for the first issue, it's a personal preference, really. The algorithm that YAPF uses basically decides that one way is "better" than the other. There's no clear answer to which is best. If I can add a knob so that the user has control over it, I will at least try to. But I can't promise much since the penalty for splitting after a `(` is already `0`.

**Comment by jichu4n** [comment]
I'd also like to vote for such a knob. I can see why this is hard though; you'd have to seek back to the last open parenthesis (so nested closed parentheses would be skipped). But it'd be great as I much prefer @anntzer 's style as well.

**Comment by anntzer** [comment]
Actually, I guess this can be fixed by making the penalty of splitting after a parenthesis just a tiny bit higher than the penalty for splitting after a comma?
