### ISSUE TITLE
yapf coding style

### ISSUE THREAD

**Issue by richardasaurus** [google/yapf#85]
Can we change the coding style to follow PEP8 rather than this vomit inducing Google camelCase style?

**Comment by eliben** [comment]
This type of language is not constructive. YAPF has been developed within Google and uses Google's internal Python coding style, which is consistent among a number of programming languages. It shouldn't preclude you from using the project; if you feel unable to contribute due to the coding style used, I'm really sorry. But it's not going to change any time soon.

**Comment by richardasaurus** [comment]
Eat your own dogfood.
